create table default.transactions
(
    pk                         String,
    tran_date                  Date,
    tran_location              Int16,
    tran_division              Int32,
    tran_no                    Int32,
    tran_gross                 Decimal(15, 4),
    tran_discount              Decimal(15, 4),
    tran_net                   Decimal(15, 4),
    tran_vat                   Decimal(15, 4),
    tran_cto                   Decimal(15, 4),
    tran_cover                 Decimal(15, 4),
    tran_del_charge            Decimal(15, 4),
    tran_total                 Decimal(15, 4),
    tran_receipt               String,
    tran_service               Decimal(15, 4),
    tran_employee              String,
    trans_order_time           DateTime,
    trans_cashin_time          DateTime,
    tran_cashed_in             Bool,
    tran_customer              String,
    tran_empl_loca             Int16,
    tran_amend_count           Int16,
    tran_reprint_count         Int16,
    tran_ready_status          String,
    tran_primary_currency      String,
    tran_secondary_currency    String,
    tran_currency_rate         Decimal(15, 6),
    tran_cust_no               Int32,
    tran_cash_method           String,
    tran_discount_cust         String,
    tran_prepaid_card          String,
    tran_sales_factor          Int16,
    tran_stock_factor          Int16,
    tran_staff_factor          Int16,
    tran_comp_factor           Int16,
    tran_non_prepaid_factor    Int16,
    tran_recalculate_values    Int16,
    tran_cashin_empl_loca      Int16,
    tran_cashin_employee       String,
    tran_manual_disc_perc      Decimal(15, 2),
    tran_manual_disc_amount    Decimal(15, 2),
    tran_cust_loca             Int16,
    tran_alternate_no          Int32,
    tran_receipt_series        String,
    tran_receipt_series_number Int32,
    tran_cancel_series         String,
    tran_cancel_series_number  Int32,
    tran_credit_factor         Int16,
    tran_invoice_factor        Int16,
    tran_online_factor         Int16,
    tran_sales_customer        Int32,
    tran_processed             Int16,
    tran_href                  String,
    tran_driver_cashed_in      Bool,
    tran_barter_card           String,
    division_name              String,
    receipt_method_description String,
    brand                      String,
    cash_method_description    String,
    dim_division_group         String,
    dim_division_group_source  String,
    dim_division_group_channel String,
    dim_division_group_name    String,
    location_name              String,
    receipt_category           String,
    receipt_category2          String,
    store_brand                String,
    store_mall                 String,
    store_country              String,
    store_company              String,
    store_bi_name              String,
    store_trading_nature       String
)
    engine = MergeTree PARTITION BY toYYYYMM(tran_date)
        ORDER BY (tran_date, tran_location, tran_division, tran_no)
        SETTINGS index_granularity = 8192;

        create table default.transaction_details
        (
            pk                      String,
            transactionid           String,
            trde_date               Date,
            trde_location           Int16,
            trde_division           Int32,
            trde_no                 Int32,
            trde_line               Int16,
            trde_sub_line           Int16,
            trde_item               String,
            trde_gross_price        Decimal(15, 8),
            trde_discount           Decimal(15, 4),
            trde_vat                Decimal(15, 4),
            trde_cto                Decimal(15, 2),
            trde_service            Decimal(15, 2),
            trde_comment            String,
            trde_size               String,
            trde_type               String,
            trde_qty                Int32,
            trde_vat_value          Decimal(15, 8),
            trde_cto_value          Decimal(15, 8),
            trde_service_value      Decimal(15, 8),
            trde_net_value          Decimal(15, 8),
            trde_gross_value        Decimal(15, 8),
            trde_net_price          Decimal(15, 8),
            trde_promo_perc         Decimal(15, 2),
            trde_loyalty_points     Int32,
            trde_print              Bool,
            trde_printed            Bool,
            trde_print_level        Int16,
            trde_recorded_time      String,
            trde_void_time          String,
            trde_sent_to_dev_scr    Bool,
            trde_prepaid_card       String,
            trde_prepaid_amount     Decimal(15, 2),
            trde_combo_item         String,
            trde_combo_item_group   Int16,
            trde_combo_item_pos     Int16,
            trde_vat_code           String,
            trde_line_discount      Decimal(15, 2),
            trde_empl_loca          Int16,
            trde_employee           String,
            trde_print_on_receipt   Int16,
            trde_weight             Decimal(15, 3),
            trde_qty_ratio          Decimal(15, 4),
            trde_normal_price       Decimal(15, 4),
            trde_coupon             String,
            trde_coupon_group       Int32,
            trde_is_coupon          Int32,
            trde_is_master_item     Int32,
            trde_cooking_start_time DateTime,
            trde_station            String,
            trde_void_station       String,
            trde_order_form_series  String,
            trde_order_form_number  Int32,
            trde_void_series        String,
            trde_void_series_number Int32,
            trde_recipe_ratio       Decimal(15, 4),
            trde_released_time      String,
            trde_old_division       Int32,
            trde_old_no             Int32,
            trde_old_line           Int16,
            trde_old_recorded_time  String,
            item_name               String,
            item_category           String,
            item_subcategory        String,
            item_short_description  String,
            brand                   String
        )
            engine = MergeTree PARTITION BY toYYYYMM(trde_date)
                ORDER BY (trde_date, trde_location, trde_division, trde_no, trde_line, trde_sub_line)
                SETTINGS index_granularity = 8192;
        
